[[filters]]
name = "URL House"
url = "https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt"

[[filters]]
name = "AdAway Default Blocklist"
url = "https://adaway.org/hosts.txt"

[machine]
hostname = "adguard"

[user]
username = "stan"
no_password = true
initial_password = "test123"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGSbN9/0OEdgUhNxuq+zLspbK6bd+HyDVdlfOO7O+toW noname"
